<a href="https://colab.research.google.com/github/SangamSilwal/DeepLearning_DSeries/blob/main/T1_tensors_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.9.0+cu126


# Creating Tensors

In [5]:
# using empty
a = torch.empty(2,3)
print(type(a))
a

<class 'torch.Tensor'>


tensor([[ 3.9358e-08,  0.0000e+00, -3.3535e-06],
        [ 4.4039e-41, -3.3535e-06,  4.4039e-41]])

In [6]:
#using zero
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
# using rand
torch.rand(2,3)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [9]:
# use of seed
torch.manual_seed(100)
print(torch.rand(2,3))
print(torch.rand(2,3))

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])


In [10]:
torch.manual_seed(100)
print(torch.rand(2,3))
print(torch.rand(2,3))

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])


In [15]:
# using tensor
torch.tensor([[[1,2,3],[2,3,4]]]).shape

torch.Size([1, 2, 3])

In [18]:
#other ways to create tensor

# arange
print("using arange-> ",torch.arange(0,10,2))

# using linespace
print("using linespace-> ",torch.linspace(0,10,10))

# using eye
print("using eye-> ",torch.eye(5,5))  #identity matrix

# using full
print("using full-> ",torch.full((3,3),6))

using arange->  tensor([0, 2, 4, 6, 8])
using linespace->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full->  tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])


In [27]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x.shape)

y = torch.full((4,4),7)
y

torch.Size([2, 3])


tensor([[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]])

In [20]:
torch.empty_like(x)

tensor([[788068352, 789638128,         0],
        [        0,         0,         0]])

In [21]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [22]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [28]:
y.dtype

torch.int64

In [30]:
# assign data type
torch.tensor([1.0,2.0,3.6],dtype=torch.int64)

tensor([1, 2, 3])

In [32]:
torch.rand_like(x,dtype=torch.float)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])