<a href="https://colab.research.google.com/github/SangamSilwal/DeepLearning_DSeries/blob/main/T2_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [13]:
x = torch.tensor([1],requires_grad=True,dtype=torch.float32)
y = x**2
# To calculate the gradient we need to write require_grad=True

In [14]:
x

tensor([1.], requires_grad=True)

In [15]:
y

tensor([1.], grad_fn=<PowBackward0>)

In [16]:
z = torch.sin(y)

In [17]:
z.backward()

In [19]:
z

tensor([0.8415], grad_fn=<SinBackward0>)

In [18]:
x.grad

tensor([1.0806])

In [20]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [21]:
w = torch.tensor(1.0,requires_grad=True)
b = torch.tensor(0.0,requires_grad=True)

In [22]:
w

tensor(1., requires_grad=True)

In [23]:
b

tensor(0., requires_grad=True)

In [24]:
z = w*x + b

In [25]:
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [26]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [28]:
import torch.nn.functional as F

In [29]:
loss = F.binary_cross_entropy(y_pred,y)
loss

tensor(6.7012, grad_fn=<BinaryCrossEntropyBackward0>)

In [30]:
loss.backward()

In [32]:
w.grad

tensor(6.6918)

In [33]:
b.grad

tensor(0.9988)

In [34]:
x = torch.tensor([1.0,2.0,3.0],requires_grad=True)

In [36]:
y = (x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [37]:
y.backward()
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [38]:
# Clearing Grad
x = torch.tensor(2.0,requires_grad=True)
x

tensor(2., requires_grad=True)

In [50]:
y = x**2

In [51]:
y

tensor(4., grad_fn=<PowBackward0>)

In [52]:
y.backward()

In [53]:
x.grad

tensor(4.)

In [54]:
x.grad.zero_()

tensor(0.)

In [56]:
# Disable Gradient tracking
x.requires_grad_(False)


tensor(2.)

In [57]:
x

tensor(2.)

In [59]:
# Detach
x = torch.tensor(2.0,requires_grad=True)
x

tensor(2., requires_grad=True)

In [60]:
z = x.detach()

In [61]:
z

tensor(2.)

In [62]:
# torch.no_grad -> function
x = torch.tensor(1.0,requires_grad=True)
x

tensor(1., requires_grad=True)

In [63]:
with torch.no_grad():
  y = x**2

In [64]:
y

tensor(1.)

In [65]:
x

tensor(1., requires_grad=True)