<a href="https://colab.research.google.com/github/SangamSilwal/DeepLearning_DSeries/blob/main/T4_NN_Modules.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn


In [27]:
class Model(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out = self.network(features)
    return out

In [28]:
features = torch.rand(10,5)

In [29]:
features

tensor([[0.8791, 0.6689, 0.1835, 0.6752, 0.3445],
        [0.7151, 0.3537, 0.1298, 0.2355, 0.9928],
        [0.7288, 0.3647, 0.4799, 0.3909, 0.5603],
        [0.9871, 0.0840, 0.3195, 0.1225, 0.7719],
        [0.1943, 0.3915, 0.2546, 0.4086, 0.9116],
        [0.2408, 0.0018, 0.4471, 0.6398, 0.6203],
        [0.8907, 0.7081, 0.6406, 0.1358, 0.5836],
        [0.8845, 0.8593, 0.6481, 0.7405, 0.5060],
        [0.2881, 0.5753, 0.1939, 0.0026, 0.9226],
        [0.2859, 0.8272, 0.1974, 0.7079, 0.8215]])

In [30]:
model = Model(features.shape[1])
model(features)

tensor([[0.6637],
        [0.6467],
        [0.6521],
        [0.6486],
        [0.6360],
        [0.6404],
        [0.6550],
        [0.6774],
        [0.6254],
        [0.6533]], grad_fn=<SigmoidBackward0>)

In [25]:
model.linear1.bias

Parameter containing:
tensor([-0.4260, -0.2463, -0.0847], requires_grad=True)

In [26]:
model.linear1.weight

Parameter containing:
tensor([[ 0.3545, -0.3510,  0.2488,  0.1945, -0.0827],
        [ 0.1838,  0.0424, -0.3708, -0.4166, -0.3570],
        [ 0.1304,  0.3169, -0.3177, -0.4403,  0.2534]], requires_grad=True)

In [32]:
for i in model.parameters():
  print(i)

Parameter containing:
tensor([[ 0.3076,  0.1270,  0.1010,  0.3054,  0.0752],
        [ 0.1495,  0.2530, -0.1912, -0.0190, -0.3651],
        [ 0.4305, -0.3459, -0.4118,  0.2386, -0.2660]], requires_grad=True)
Parameter containing:
tensor([ 0.0339,  0.2821, -0.4092], requires_grad=True)
Parameter containing:
tensor([[ 0.5292, -0.0651, -0.1754]], requires_grad=True)
Parameter containing:
tensor([0.3677], requires_grad=True)


In [ ]:
# optimizer = torch.optim.SGD(model.parameters(),lr=0.01)
# optimizer.zero_grad()
# optimizer.step()